[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.zip", "php82Extensions.exif", "php82Extensions.pcntl", "php82Extensions.gd", "composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = ["php artisan config:clear", "php artisan cache:clear"]

[start]
cmd = "bash start.sh"